AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false
  CacheRootDirectory: tmp
  Exclude:
    - vendor/**/*
    - planning/**/*
    - tmp/**/*

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler/OrderedGems:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Metrics/ParameterLists:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 120
